// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ZZ0Tz4Kn7FIwKJFprcrpDJDwdRtNAnc',
    appId: '1:919297115279:web:dda22fd8d03be45b755cfa',
    messagingSenderId: '919297115279',
    projectId: 't2xpro',
    authDomain: 't2xpro.firebaseapp.com',
    storageBucket: 't2xpro.appspot.com',
    measurementId: 'G-3MLXGLGQX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD604nopyDrHF_dNMMWMG-w44SkikSd-Rw',
    appId: '1:919297115279:android:22776131215d03ec755cfa',
    messagingSenderId: '919297115279',
    projectId: 't2xpro',
    storageBucket: 't2xpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMxzQCdPzfGBOMJv7geT0bv81non5mkzA',
    appId: '1:919297115279:ios:121ac0eae3e712e2755cfa',
    messagingSenderId: '919297115279',
    projectId: 't2xpro',
    storageBucket: 't2xpro.appspot.com',
    iosBundleId: 'com.example.mobileOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMxzQCdPzfGBOMJv7geT0bv81non5mkzA',
    appId: '1:919297115279:ios:08573cfadece5b06755cfa',
    messagingSenderId: '919297115279',
    projectId: 't2xpro',
    storageBucket: 't2xpro.appspot.com',
    iosBundleId: 'com.example.mobileOtp.RunnerTests',
  );
}
